class Product {
  final String title;
  final String description;
  final double price;
  final double originalPrice;
  final double discount;
  final int reviews;
  final String imagePath;

  Product({
    required this.title,
    required this.description,
    required this.price,
    required this.originalPrice,
    required this.discount,
    required this.reviews,
    required this.imagePath,
  });
}

List<Product> listOfProducts = [
  Product(
    title: 'Nike Air Max 90',
    description:
        'Legendary sneakers with a classic design and maximum comfort.',
    price: 1500.0,
    reviews: 120,
    imagePath: 'assets/images/sneakers 1.jpg',
    originalPrice: 3000.0,
    discount: 50.0,
  ),
  Product(
    title: 'Adidas Ultraboost 22',
    description: 'High-performance running sneakers with unmatched cushioning.',
    price: 1500.0,
    reviews: 120,
    imagePath: 'assets/images/sneakers 2.jpg',
    originalPrice: 3000.0,
    discount: 50.0,
  ),
  Product(
    title: 'Puma RS-X3',
    description: 'Stylish retro-inspired sneakers with bold colors.',
    price: 1500.0,
    reviews: 120,
    imagePath: 'assets/images/sneakers 3.jpg',
    originalPrice: 3000.0,
    discount: 50.0,
  ),
  Product(
    title: 'New Balance 574',
    description: 'Timeless sneakers that combine style and functionality.',
    price: 1500.0,
    reviews: 120,
    imagePath: 'assets/images/sneakers 4.jpg',
    originalPrice: 3000.0,
    discount: 50.0,
  ),
  Product(
    title: 'Nike ZoomX Invincible',
    description: 'Lightweight sneakers designed for long-distance running.',
    price: 1800.0,
    reviews: 95,
    imagePath: 'assets/images/sneakers 1.jpg',
    originalPrice: 3600.0,
    discount: 50.0,
  ),
  Product(
    title: 'Adidas NMD R1',
    description: 'Modern sneakers with a sleek design and adaptive fit.',
    price: 2000.0,
    reviews: 150,
    imagePath: 'assets/images/sneakers 2.jpg',
    originalPrice: 4000.0,
    discount: 50.0,
  ),
  Product(
    title: 'Puma Future Rider',
    description: 'Comfortable and stylish sneakers for everyday wear.',
    price: 1400.0,
    reviews: 110,
    imagePath: 'assets/images/sneakers 3.jpg',
    originalPrice: 2800.0,
    discount: 50.0,
  ),
  Product(
    title: 'New Balance 327',
    description: 'Vintage-inspired sneakers with a contemporary twist.',
    price: 1600.0,
    reviews: 130,
    imagePath: 'assets/images/sneakers 4.jpg',
    originalPrice: 3200.0,
    discount: 50.0,
  ),
  Product(
    title: 'Nike Pegasus Trail 3',
    description: 'Durable sneakers designed for trail running.',
    price: 1700.0,
    reviews: 80,
    imagePath: 'assets/images/sneakers 1.jpg',
    originalPrice: 3400.0,
    discount: 50.0,
  ),
  Product(
    title: 'Adidas Gazelle',
    description: 'Iconic sneakers with a timeless silhouette.',
    price: 1500.0,
    reviews: 140,
    imagePath: 'assets/images/sneakers 2.jpg',
    originalPrice: 3000.0,
    discount: 50.0,
  ),
  Product(
    title: 'Puma Suede Classic',
    description: 'Classic design with a luxurious suede finish.',
    price: 1450.0,
    reviews: 125,
    imagePath: 'assets/images/sneakers 3.jpg',
    originalPrice: 2900.0,
    discount: 50.0,
  ),
  Product(
    title: 'New Balance 550',
    description: 'Retro basketball-inspired sneakers.',
    price: 1550.0,
    reviews: 100,
    imagePath: 'assets/images/sneakers 4.jpg',
    originalPrice: 3100.0,
    discount: 50.0,
  ),
  Product(
    title: 'Nike Blazer Mid 77',
    description: 'Vintage basketball sneakers with a modern touch.',
    price: 1600.0,
    reviews: 90,
    imagePath: 'assets/images/sneakers 1.jpg',
    originalPrice: 3200.0,
    discount: 50.0,
  ),
  Product(
    title: 'Adidas Superstar',
    description: 'Classic shell-toe sneakers for everyday wear.',
    price: 1500.0,
    reviews: 200,
    imagePath: 'assets/images/sneakers 2.jpg',
    originalPrice: 3000.0,
    discount: 50.0,
  ),
  Product(
    title: 'Puma Cali',
    description: 'Fashion-forward sneakers with a laid-back vibe.',
    price: 1400.0,
    reviews: 85,
    imagePath: 'assets/images/sneakers 3.jpg',
    originalPrice: 2800.0,
    discount: 50.0,
  ),
  Product(
    title: 'New Balance XC-72',
    description: 'Futuristic design with vintage inspiration.',
    price: 1750.0,
    reviews: 115,
    imagePath: 'assets/images/sneakers 4.jpg',
    originalPrice: 3500.0,
    discount: 50.0,
  ),
  Product(
    title: 'Nike Air Force 1',
    description: 'Timeless sneakers with a versatile design.',
    price: 1550.0,
    reviews: 180,
    imagePath: 'assets/images/sneakers 1.jpg',
    originalPrice: 3100.0,
    discount: 50.0,
  ),
  Product(
    title: 'Adidas Yeezy Boost 350',
    description: 'Premium sneakers with innovative design.',
    price: 2200.0,
    reviews: 300,
    imagePath: 'assets/images/sneakers 2.jpg',
    originalPrice: 4400.0,
    discount: 50.0,
  ),
  Product(
    title: 'Puma Ignite',
    description: 'Performance sneakers with energy-return technology.',
    price: 1600.0,
    reviews: 105,
    imagePath: 'assets/images/sneakers 3.jpg',
    originalPrice: 3200.0,
    discount: 50.0,
  ),
  Product(
    title: 'New Balance Minimus',
    description: 'Lightweight sneakers for minimalist running.',
    price: 1450.0,
    reviews: 95,
    imagePath: 'assets/images/sneakers 4.jpg',
    originalPrice: 2900.0,
    discount: 50.0,
  ),
  Product(
    title: 'Nike Free RN 5.0',
    description: 'Natural motion sneakers for a barefoot feel.',
    price: 1400.0,
    reviews: 125,
    imagePath: 'assets/images/sneakers 1.jpg',
    originalPrice: 2800.0,
    discount: 50.0,
  ),
];
